project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands_on_Ex1.html
          - text: Hands-on Exercise 2
            href: Hands_on_Ex2.html
          - text: Hands-on Exercise 3
            href: Hands-on-Ex3.html
      - text: In-class Exercise
        menu: 
          - text: In-class Exercise 2
            href: In_class_Ex2.html
          - text: In-class Exercise 2:GLSA
            href: In_class_Ex2_GLSA.html
          - text: In-class Exercise 2:EHSA
            href: In_class_Ex2_EHSA.html
          - text: In-class Exercise 3
            href: In-class_Ex3.html
          - text: In-class Exercise 4
            href: In_class_Ex4.html
      - text: Take-home Exercise
        menu: 
          - text: Take-home Exercise 1
            href: Take_home_Ex1.html
          - text: Take-home Exercise 2
            href: Take_home_Ex2.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

