project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Exercise 1
            href: Hands_on_Ex1.html
          - text: Hands-on Exercise 2
            href: Hands_on_Ex2.html
          - text: Hands-on Exercise 3
            href: Hands-on-Ex3.html
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

